# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76e04fb23b93e249d0e008e83916202556b98778d529e3e12a461ab8071bf4b25f5a3546419931d37093dc9a8800bc877c5e8713dd63e52fd2050eab9458d13b

test:
  secret_key_base: e235d176c16fc9c7af83033d62bd0c5b2213fe1d13f2743322dc92065100ead901f2797b3955757fb9083e7225c27db1ce259427650044bc26587a82c6aecb60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
